language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, needed for cypress
      - libgconf-2-4
  sonarcloud:
    organization: "matt-dunn"
    token:
      secure: "PCYJ/ZPDisrk6NH+377krCsL/NegvmsNRKYraS7HVoswwba2zdPCOjPbvs8wcOQsQmEO75YU2Z55vUt1vYeVHIMyWCZnRo8R9IpKU0kAFwLA3Gsa84+cshntRRfthV4WKLs6RaidyR7ma7SKM89xIZwjSDdpHTYKkRMiZ6Ig3tsWNXlvbd2IK4kfBx4UbPkRyAOTiYC1WirhK3XSwUEkedPG/XEAEptjvoHeBOGLzwen/Fz/dzEtPgZI08kPmda2XbI5I2+RzgkGljkBSfkfsL/wrp31Oese5Uj/QKU83zS0/qle27Uvrc7/AanGDe+YvJUkTESkbjkMqzFgLg8rE7huhVrFq1RHkA4QjsebnZu6kSZ+qtIaxW0+wh2mcFZxVOA63TfoY5zMJg8SnfYxpnh+O6K1RxLF360nIfZpx1WTxp1El3OUuWl1i3ogV/5GNhZ6610qLj/pXL/6DFG1/ItbTt8ikNSkhIe8hs+4hrbMgHN4w7cXZEKijyLJwAFrcHJgXzB+H/gK2ukdhjtRXBBhMjdIsic6OPavhGoRFOGjzG7zGKK3gHoDGm59Mq/6EoKJu9xRQPVdfrpQAF4lB73GThpPo0Cs4kG23UIkFthHo8sDikDdfY0QescrWB5dGTxjfMRzQsQ8bCQD8hFDatNjurR4wD+rqQ7Y1M6R3KQ="
cache:
  npm: true
  yarn: true
  directories:
    - ~/.cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.19.2
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist
  on:
    branch: master
script:
  - yarn ci
  - sonar-scanner
