language: node_js
node_js:
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.19.2
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist
  on:
    branch: master
script:
  - yarn build:all
