name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v2.0.0
    - name: Install
      run: yarn install
    - name: Build
      run: yarn ci
    - uses: mathrix-education/sonar-scanner@master
      with:
        version: 4.2.0.1873 # required
        typescript: true
        scan: true
        args: --debug -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    env:
      CI: true


