# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, cu-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: GitHub Action for Yarn + Cypress
      uses: KingScooty/actions-yarn-cy@1.0.0
    - name: sonar-scanner
      uses: Warchant/setup-sonar-scanner@v1
    - run: yarn install
    - run: yarn ci
      env:
        CI: true
